### ISSUE TITLE
Doesn't work with JIRA 6

### ISSUE THREAD

**Issue by hco** [it-agile/JimFlowJira#1]
Maybe I did something wrong, but with JIRA 6 all I get is textfield with the URL.

Are you still maintaining this? Otherwise I could try to fix it myself, but I guess for you this is probably a couple of minutes work, so I decided to ask first :)

**Comment by lomin** [comment]
Hi Hans-Christian,

I do not own a JIRA 6 license, so it would be pretty cool if you could fix
this and send me a pull request!

Regards,
Steven

2013/7/17 Hans-Christian Otto notifications@github.com

> Maybe I did something wrong, but with JIRA 6 all I get is textfield with
> the URL.
> 
> Are you still maintaining this? Otherwise I could try to fix it myself,
> but I guess for you this is probably a couple of minutes work, so I decided
> to ask first :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/it-agile/JimFlowJira/issues/1
> .

## 

B.Eng. Steven Collins

it-agile GmbH, http://www.it-agile.de
Große Elbstraße 273, 22767 Hamburg
Zentrale: +49 40 41 35 848 - 0

Geschäftsführer: Henning Wolf, Jens Coldewey
Handelsregister Hamburg, HRB: 92261
Umsatzsteuer-Identifikationsnummer: DE239483021
